### ISSUE TITLE
Add new affected user tracking information

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4cfml#14]
We are adding a bit more information to the affected user tracking feature in Raygun - could you add support for it as well?

Here it is in the Raygun .Net provider:
https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/Messages/RaygunIdentifierMessage.cs
And the documentation for it is here:
https://github.com/MindscapeHQ/raygun4net#affected-user-tracking

Cheers,
Jamie

**Comment by TheRealAgentK** [comment]
That's done. @jamiepenney, however it seems that UUID even though being passed in correctly (from what I can see) does never get shown in the Dashboard interface. Anything I'm missing?

**Comment by jamiepenney** [comment]
Nah there's nothing on the dashboard, we've got some stuff in the works that will use the UUID but nothing visible yet.

**Comment by kennethwsmith** [comment]
Great Job Agent K!  Thanks
