### ISSUE TITLE
Is it possible to set the versiontracking with raygun4cfml?

### ISSUE THREAD

**Issue by linuxonrails** [MindscapeHQ/raygun4cfml#33]
I know we can use versiontracking with other languages: 

https://raygun.com/docs/languages/javascript#versiontracking

**Comment by TheRealAgentK** [comment]
Yeah, that'd actually be quite easy to do from inside the API. 

How would you envisage the syntax to pass it into the Raygun API call to work and look like? Any suggestion?

**Comment by TheRealAgentK** [comment]
It could be as simple as:

raygun.send(issueDataStruct=error,userCustomData=customUserData,...,appVersion="1.2.3.4");

Would that suit?

**Comment by linuxonrails** [comment]
It would be perfect with another param `appVersion`!

**Comment by linuxonrails** [comment]
something new?

**Comment by TheRealAgentK** [comment]
Completed
