### ISSUE TITLE
raw data is truncated

### ISSUE THREAD

**Issue by neiloflions** [MindscapeHQ/raygun4cfml#42]
Hello

There's code within RaygunRequestMessage.cfc that truncates everything but the first 4096 characters of the rawData.
For the project I'm working on I've increased this value to 32768 as it was truncating most of the payload from our api.
Can this truncation be safely removed from code?

**Comment by TheRealAgentK** [comment]
I'll need to double-check with someone from the team, @neiloflions. There is a limit on the overall payload that can be sent in one push to RG, but I'm not 100% sure if that breaks down into particular fields.

@mduncan26 - would you have any input on that?

**Comment by mduncan26** [comment]
Hi @neiloflions 

Sorry for the late followup. The 4096 character limit is our default limit when capturing raw data from a request body. This is the same limit we have in our .NET SDKs. 

The intention behind this is to avoid automatically capturing too much information resulting in the error report being rejected by our API for being too large. We have max error report limit of 128kb, if over this limit it will be rejected by our API.

We are open to providing ways of increasing this limit. Perhaps a way of setting the desired limit with a default of 4096 still in place. Please feel free to open a pull request if you wish and we can consider this further.

Thanks :)

**Comment by TheRealAgentK** [comment]
Closing and adding a setting in the future to override the limit. #49
