### ISSUE TITLE
Compatible with CF 2023 and Java 17?

### ISSUE THREAD

**Issue by crazygoji1** [MindscapeHQ/raygun4cfml#56]
We are getting this error trying to run raygun4cfml on CF 2023 and Java 17.0.9

java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.management.MemoryImpl.gc() accessible: module java.management does not "opens sun.management" to unnamed module @353f472a

The error occurred in E:/inetpub/raygun4cfml/RaygunEnvironmentMessage.cfc: line 34

Does anything have to be added to the java.args in  jvm.config?

**Comment by TheRealAgentK** [comment]
Hey @crazygoji1 - thx for the report.

It seems it's failing on `mf.getMemoryMXBean().getHeapMemoryUsage();`. That used to be accessible pre ACF2023 and Java 17.

If you have control over your JVM arguments, you *should* (and I haven't tried that yet) be able to allow the access via:

```
--add-opens java.management/sun.management=ALL-UNNAMED
```

(And I'll try and document that as well accordingly over the weekend)

But regardless - I'll need to move that call that's now in line 34 into a try catch in a quick patch release to avoid it causing issues. That'll come out soon, I'll aim for today.

**Comment by TheRealAgentK** [comment]
Fixed in 1.7.0
